export const SET_USER = "SET_USER";

export const SET_TOKEN = "SET_TOKEN";

export const SET_FOLLOWERS = "SET_FOLLOWERS";

export const SET_FOLLOWING = "SET_FOLLOWING";

export const GITHUB_SIGN_IN_START = "GITHUB_SIGN_IN_START"
export const GITHUB_SIGN_IN_SUCCESS = "GITHUB_SIGN_IN_SUCCESS"
export const GITHUB_SIGN_IN_FAIL = "GITHUB_SIGN_IN_FAIL"

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";


export const SET_REPOSITORIES = "SET_REPOSITORIES";
export const SELECTED_REPOSITORY = "SELECTED_REPOSITORY";
export const REMOVE_SELECTED_REPOSITORY = "REMOVE_SELECTED_REPOSITORY";

export const SET_STARRED_REPOSITORIES = "SET_STARRED_REPOSITORIES";
export const SET_SEARCHED_STARRED_REPOSITORIES = "SET_SEARCHED_STARRED_REPOSITORIES";
export const REMOVE_STARRED_REPOSITORY = "REMOVE_STARRED_REPOSITORY";
export const ADD_STARRED_REPOSITORY = "ADD_STARRED_REPOSITORY";